#!/usr/bin/python

import sys, re, os

path = os.path.abspath(__file__)

try: curlist = eval(open(path.replace('main','curlist'),'r').read())
except:
	open(path.replace('main','curlist'),'w').write('[]')
	curlist = []

items = sys.argv[1:]

while items and re.match('^[1-9]+$',items[0]):
	if int(items[0]) <= len(curlist): curlist[int(items[0])-1] = ''
	items.remove(items[0])

curlist = curlist[::-1]

cilist = map(lambda x: x.lower,curlist)
for item in items:
        if item.lower() in cilist:
                curlist[cilist.index(item.lower())] = ''
        else: curlist.append(item)
while '' in curlist:
	curlist.remove('')

for i in curlist[::-1]:
	print "%d: %s" %(curlist[::-1].index(i)+1,i)
if not curlist:
	print "Todo list is empty!"

open(path.replace('main','curlist'),'w').write(str(curlist[::-1]))

